language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("MultivariateStats.jl"); Pkg.test("MultivariateStats.jl"; coverage=true)';
    - julia -e 'cd(Pkg.dir("MultivariateStats.jl")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

